#
# This file uses the crosswalk generated by ./crosswalk/census.R to crosswalk Asian voting age population.
# CVAP by race specifically does not seem to be in tidycensus, excpet 2019 acs1/subject.
#

bg_crosswalk <- read.csv("./crosswalk/bg2010_bg2020.csv")

# Notable columns:
# - CIT_EST: rounded estimate of total number of citizens
# - CVAP_EST: rounded estimate of total number of citizens >= 18 years old
cvap2010 <- read.csv("./cvap/CVAP_2010.csv") %>%
  mutate(GEOID = substr(GEOID, 8, 19)) %>%
  select(GEOID, group = LNTITLE, value = CVAP_EST)

cvap2019 <- read.csv("./cvap/CVAP_2019.csv") %>%
  mutate(GEOID = substr(geoid, 8, 19)) %>%
  select(GEOID, group = lntitle, value = cvap_est)

#
# Convert both to 2020 block groups
#

bg_crosswalk %>% 
  inner_join(bg_pop_2010 %>% rename(blk_group10 = blk_group), by = "blk_group10") %>%
